name: e2e

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    e2e:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macOS-latest]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 15.x
              uses: actions/setup-node@v1
              with:
                  node-version: 15.x
            - name: NPM Setup
              uses: filipstefansson/set-npm-token-action@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
            - name: install server
              run: npm ci
              env:
                  NPM_TOKEN: $${ secrets.NPM_TOKEN }
            - name: Copy NPM config
              run: cp ./.npmrc ./client/.npmrc && cp ./.npmrc ./reporter-client/.npmrc
            - name: install client
              run: (cd client && npm ci) && (cd reporter-client && npm ci)
              env:
                  NPM_TOKEN: $${ secrets.NPM_TOKEN }
            - name: build
              run: npm run build
            - name: e2e-test
              run: npm run test:e2e
              env:
                  CI: true
