name: Linux Release

on: [push]

jobs:
    release-linux:
        runs-on: ubuntu-latest

        
        strategy:
            matrix:
                node-version: [10.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install
              run: npm ci
            - name: Build
              run: npm run build
            - name: Install Snapcraft
              uses: samuelmeuli/action-snapcraft@v1
            - name: Publish Linux
              run: npm run publish:linux
              env:
                  CI: true